In [1]:
import sys 
x= int(input(sys.argv[1]))
y= int(input(sys.argv[2]))
z=x+y
print("output is", z)


-f23
C:\Users\Hacker\AppData\Roaming\jupyter\runtime\kernel-0967ec58-af1a-4223-88e1-5fc0594ed888.json32
output is 55


In [2]:
import array as arr
arr.array()


TypeError: array() takes at least 1 argument (0 given)

In [3]:
from array import *
value= array('i',[5,6,3,3,2,5])
print (value)


array('i', [5, 6, 3, 3, 2, 5])


In [4]:
from array import *
value= array('i',[5,6.5,3,3,2,5])
print (value)

TypeError: integer argument expected, got float

In [5]:
from array import *
vals=array('i',[5,4,2,4,6])
vals.reverse()
print(vals)


array('i', [6, 4, 2, 4, 5])


In [7]:
# floor=lowest integer value nearby
# ceil= highest integer value near by

In [8]:
#  ~ = tilde operator
#   ^ = XOR
#   <<= Left shift
#   >>= Right shift

In [9]:
import math as m
x=8.9
x=m.floor(x)
print(x)

8


In [10]:
import math as m
x=8.9
x=m.ceil(x)
print(x)

9


In [11]:
from array import *
vals=array('i',[5,4,2,4,6])
vals.reverse()
print(vals)
newarr= array(vals.typecode, (a for a in vals))
print(newarr)
for e in vals:
    print(e)

array('i', [6, 4, 2, 4, 5])
array('i', [6, 4, 2, 4, 5])
6
4
2
4
5


In [12]:
from array import *
vals=array('i',[5,4,2,4,6])
vals.reverse()
print(vals)
newarr= array(vals.typecode, (a*a for a in vals))
print(newarr)
for e in vals:
    print(e)

array('i', [6, 4, 2, 4, 5])
array('i', [36, 16, 4, 16, 25])
6
4
2
4
5


In [13]:
# searching a value index from an array
from math import *
from array import *
arr=array('i',[])
n=int(input("Enter the length of an array"))

for i in range(n):
    x= int(input("Enter the next value"))
    arr.append(x)

print(arr)

val= int(input("enter the value for search"))

k=0
for y in arr:

    if y==val:
        print(k)
        break
        
    k+=1    

Enter the length of an array4
Enter the next value2
Enter the next value3
Enter the next value4
Enter the next value5
array('i', [2, 3, 4, 5])
enter the value for search4
2


In [14]:
import numpy

In [15]:
from numpy import *
arr = linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [16]:
from numpy import *
arr = logspace(0,15,16)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15]


In [17]:
from numpy import *
arr = arange(0,15,12)
print(arr)

[ 0 12]


In [18]:
from numpy import *
arr= array([23,33,43,53])
arr=arr+12
print(arr)

[35 45 55 65]


In [19]:
from numpy import *
arr1= array([34,22,44,24])
arr2=array([11,13,21,31])
arr3=arr1+arr2
print(arr3)

[45 35 65 55]


In [20]:
from numpy import *
arr1= array([34,22,44,24])
arr2=array([11,13,21,31])
arr3=arr1+arr2
print(sum(arr3))

200


In [21]:
from numpy import *
arr1= array([34,22,44,24])
arr2=array([11,13,21,31])
print(concatenate([arr1,arr2]))

[34 22 44 24 11 13 21 31]


In [22]:
# shallow copy of an array
from numpy import *
arr1= array([1,2,3,4,5,6])
arr2=arr1.view()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
2888472436128
2888472433328


In [23]:
# deep copy of an array
from numpy import *
arr1= array([1,2,3,4,5,6])
arr2=arr1.copy()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
2888476670272
2888476670912


In [24]:
# multi-dimensional array
from numpy import *
arr1= array([
                [1,2,3],
                [4,5,6]
            ])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [25]:
# multi-dimensional array dimension
from numpy import *
arr1= array([
                [1,2,3],
                [4,5,6]
            ])
print(arr1.ndim)

2


In [26]:
# multi-dimensional array shape
from numpy import *
arr1= array([
                [1,2,3],
                [4,5,6]
            ])
print(arr1.shape)

(2, 3)


In [27]:
# multi-dimensional array size
from numpy import *
arr1= array([
                [1,2,3],
                [4,5,6]
            ])
print(arr1.size)

6


In [28]:
# multi-dimensional array to single dimensional
from numpy import *
arr1= array([
                [1,2,3],
                [4,5,6]
            ])
arr2= arr1.flatten()
print(arr2)

[1 2 3 4 5 6]


In [29]:
# multi-dimensional array to two dimensional 3D array
from numpy import *
arr1= array([
                [1,2,3,4,5,6],
                [4,5,6,7,8,9]
            ])
arr2= arr1.flatten()
arr3= arr2.reshape(2,2,3)
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [30]:
from numpy import *
m= matrix('1 2; 3 4; 5 6; 7 8')
print(m)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
from numpy import *
m= matrix('1 2 3; 4 5 6; 7 8 9')
print(diagonal(m))

[1 5 9]


In [32]:
from numpy import *
m= matrix('1 2 3; 4 5 6; 7 8 9')
print(m.min())

1


In [33]:
from numpy import *
m= matrix('1 2 3; 4 5 6; 7 8 9')
print(m.max())

9


In [34]:
# matrix multiplication
from numpy import *
m1= matrix('1 2 3; 5 6 7; 7 8 9')
m2= matrix('5 6 7; 8 9 0; 1 2 4')
m3= m1*m2
print (m3)

[[ 24  30  19]
 [ 80  98  63]
 [108 132  85]]


In [35]:
#function 
def sum(x,y):
    z=x+y
    print(z)

sum(5,6)

11


In [36]:
# there is no pass by value and pass by reference functions in python

In [37]:
# WAP to count even and odd numbers in a list
from math import *
from numpy import *
def count(lst):
    even = 0
    odd = 0
    
    for i in lst:
        if i%2==0:
            even+= 1
        else: 
            odd+= 1
    return even,odd
    
lst=[12,24,33,55,22,77,88]
even, odd = count(lst)
print("Even : {} and Odd : {}".format(even,odd))


Even : 4 and Odd : 3


In [40]:
# WAP to print fibonacci series

def fib(n):
    a=0
    b=1
    print(a)
    print(b)
    
    for i in range(n-2):
        c=a+b
        a=b
        b=c
        print(c)

print("The expected series is:")
fib(10)

The expected series is:
0
1
1
2
3
5
8
13
21
34


In [42]:
# WAP to print a factorial number

def fact(n):
    f=1
    for i in range(1,n+1):
        f=f*i
    return f
result= fact(4)
print("the required factorial is",result)

the required factorial is 24


In [43]:
# Recursion limit in python is 1000 times and in jupyter is 3000.

In [44]:
# WAP to check any function limit in python.

import sys
print(sys.getrecursionlimit())

3000


In [45]:
# WAP to set fuction limit in python.
import sys
sys.setrecursionlimit(4000)
print(sys.getrecursionlimit())


4000


In [52]:
# Anonymous function(Lambda)
# WAP to print table of 2 using lambda function in python
f= lambda a,b: a*b
print("The multiplication table of 2 is")
for i in range(1,11):
    result= f(2,i)
    print("2 *",i,"=",result)

The multiplication table of 2 is
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


In [53]:
# WAP to filter even set of numbers from the given list in python.

nums=[2,3,1,6,8,7,9,40,20,33,45,44,37,28]
evens= list(filter(lambda n : n%2==0, nums))

print(evens)

[2, 6, 8, 40, 20, 44, 28]


In [54]:
# WAP to filter and mapping double of even set of numbers from the given list in python.

nums=[2,3,1,6,8,7,9,40,20,33,45,44,37,28]
evens= list(filter(lambda n : n%2==0, nums))
doubles= list(map(lambda n : n*2, evens ))
print(evens)
print(doubles)

[2, 6, 8, 40, 20, 44, 28]
[4, 12, 16, 80, 40, 88, 56]


In [56]:
# WAP to filter, mapping and reduce double of even set of numbers from the given list in python.
from functools import reduce
nums=[2,3,1,6,8,7,9,40,20,33,45,44,37,28]
evens= list(filter(lambda n : n%2==0, nums))
doubles= list(map(lambda n : n*2, evens ))
print(evens)
print(doubles)
sum= reduce(lambda  a,b : a+b, doubles)
print(sum)

[2, 6, 8, 40, 20, 44, 28]
[4, 12, 16, 80, 40, 88, 56]
296


In [58]:
# decorators in python
 
def div(a,b):
    print(a/b)
    
def smart_div(func):
    def inner(a,b):
        if a<b:
            a,b=b,a
        return func(a,b)
    return inner
div1=smart_div(div)
div1(2,4)

2.0
